### ISSUE TITLE
Getting error running

### ISSUE THREAD

**Issue by goapifirst** [TokugawaHeavyIndustries/ubv-remux-docker#1]
Tried running this.. my host is VMWare Player 16 running Ubuntu 21.04 Desktop OS.  I have copied .ubv files to my VM. When I run:

docker run --rm -v /home/k/Desktop/ubv:/remux tokugawaheavyindustries/ubv-remux-docker /remux

I get:

/usr/bin/remuxscript.sh: line 21: /usr/bin/remux-amd64: cannot execute binary file: Exec format error

Seems odd.

**Comment by TokugawaHeavyIndustries** [comment]
Is your Ubuntu installation x64 or x86?  I'm only able to reproduce this with a 32-bit OS.

**Comment by goapifirst** [comment]
X64. AMD cpu, VM is is also 64bit version of OS.

Linux ubuntu 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TokugawaHeavyIndustries** [comment]
@goapifirst Thanks for alerting me to this, I just updated the executable.  Should work now.  You'll want to remove the local image and re-pull from Docker Hub.

**Comment by TokugawaHeavyIndustries** [comment]
#c2dc4aceba9e3cf2d160c41a02a70c64fdc4304a
